/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.prograIII.appProyecto.vista;

/**
 *
 * @author Anthony Carrillo
 */
public class FacturaView extends javax.swing.JFrame {

    /**
     * Creates new form FacturaView
     */
    public FacturaView() {
        initComponents();
        this.txtIdCliente.setVisible(false);
        this.txtIdArticulo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        btBuscarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIdArticulo = new javax.swing.JTextField();
        btBuscarArticulo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTotalArt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDetalle = new javax.swing.JTable();
        btAgregar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtNombreArticulo = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        lbFecha = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        btFacturar = new javax.swing.JButton();
        agrega2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 23, -1, -1));

        jLabel2.setText("Hora");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 23, -1, -1));

        jLabel3.setText("Nombre del Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 23, 178, -1));
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 209, 23));

        btBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/find.png"))); // NOI18N
        getContentPane().add(btBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 40, 38, -1));

        jLabel4.setText("Articulo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 88, -1, -1));

        txtIdArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdArticuloActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 381, 59, -1));

        btBuscarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/find.png"))); // NOI18N
        getContentPane().add(btBuscarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 112, 38, -1));

        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 88, -1, -1));

        txtCantidad.setColumns(2);
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 122, 51, 23));

        jLabel6.setText("Valor Unidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 88, -1, -1));

        txtValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtValorUnitario.setEnabled(false);
        getContentPane().add(txtValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 122, 65, 23));

        jLabel7.setText("Valor Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 88, -1, -1));

        txtTotalArt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTotalArt.setEnabled(false);
        getContentPane().add(txtTotalArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 122, 109, 23));

        jTDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio Unitario", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTDetalle);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 116));

        btAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/agregar.png"))); // NOI18N
        btAgregar.setText("Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 100, 56));

        btEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/elimiar.png"))); // NOI18N
        btEliminar.setText("Eliminar");
        btEliminar.setMaximumSize(new java.awt.Dimension(91, 25));
        btEliminar.setMinimumSize(new java.awt.Dimension(91, 25));
        btEliminar.setPreferredSize(new java.awt.Dimension(91, 25));
        getContentPane().add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 100, 56));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("TOTAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 298, -1, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 327, 187, -1));

        txtNombreArticulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNombreArticulo.setEnabled(false);
        getContentPane().add(txtNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 122, 126, 23));

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 407, 59, -1));

        lbFecha.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 53, 90, 20));

        lbHora.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 53, 76, 20));

        btFacturar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btFacturar.setForeground(new java.awt.Color(255, 0, 0));
        btFacturar.setText("Facturar");
        btFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacturarActionPerformed(evt);
            }
        });
        getContentPane().add(btFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 298, 144, 118));

        agrega2.setText("agrega2");
        getContentPane().add(agrega2, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 6, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/fondo_video.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-430, 0, 920, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdArticuloActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAgregarActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
 
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
      
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFacturarActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
          char c = evt.getKeyChar();
          if (c<'0'|| c>'9') evt.consume();
    }//GEN-LAST:event_txtCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agrega2;
    public javax.swing.JButton btAgregar;
    public javax.swing.JButton btBuscarArticulo;
    public javax.swing.JButton btBuscarCliente;
    public javax.swing.JButton btEliminar;
    public javax.swing.JButton btFacturar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTDetalle;
    public javax.swing.JLabel lbFecha;
    public javax.swing.JLabel lbHora;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtIdArticulo;
    public javax.swing.JTextField txtIdCliente;
    public javax.swing.JTextField txtNombreArticulo;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtTotalArt;
    public javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables
}
