/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.prograIII.appProyecto.vista;

/**
 *
 * @author Kevin
 */
public class PantallaPrincipal extends javax.swing.JFrame  {
           
     public PantallaPrincipal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jMenuItem3 = new javax.swing.JMenuItem();
        btLimpiarPantalla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPC = new javax.swing.JTable();
        btIniciarServidor = new javax.swing.JButton();
        btDetenerServidor = new javax.swing.JButton();
        btBloquear = new javax.swing.JButton();
        btDesbloquear = new javax.swing.JButton();
        btEnviar = new javax.swing.JButton();
        btFacturar = new javax.swing.JButton();
        txtMensaje = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Chat_Servidor = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        MenuBarPrincipal = new javax.swing.JMenuBar();
        menuMantenimientos = new javax.swing.JMenu();
        menuManteCliente = new javax.swing.JMenuItem();
        menuManteArticulo = new javax.swing.JMenuItem();
        menuManteProveedor = new javax.swing.JMenuItem();
        menuManteArtProv = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        mReporteClientes = new javax.swing.JMenuItem();
        mReporteArticulos = new javax.swing.JMenuItem();
        mReporteFacturas = new javax.swing.JMenuItem();
        mReporteProveedores = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jButton1.setText("jButton1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLimpiarPantalla.setBackground(new java.awt.Color(255, 255, 255));
        btLimpiarPantalla.setText("Limpiar pantalla");
        btLimpiarPantalla.setPreferredSize(new java.awt.Dimension(115, 23));
        btLimpiarPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarPantallaActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpiarPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 274, 145, -1));

        jTPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "IP", "Estado", "Hora Inicio", "Hora Fin"
            }
        ));
        jScrollPane2.setViewportView(jTPC);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 303, 505, 107));

        btIniciarServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/chronometer.png"))); // NOI18N
        btIniciarServidor.setText("Iniciar ");
        getContentPane().add(btIniciarServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 417, 25, 27));

        btDetenerServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/media_playback_stop.png"))); // NOI18N
        btDetenerServidor.setText("Detener ");
        getContentPane().add(btDetenerServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 427, 23, 20));

        btBloquear.setBackground(new java.awt.Color(255, 255, 255));
        btBloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/Block.png"))); // NOI18N
        btBloquear.setText("Bloquear");
        getContentPane().add(btBloquear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 161, -1));

        btDesbloquear.setBackground(new java.awt.Color(255, 255, 255));
        btDesbloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/Desblock.png"))); // NOI18N
        btDesbloquear.setText("Desbloquear");
        btDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesbloquearActionPerformed(evt);
            }
        });
        getContentPane().add(btDesbloquear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btEnviar.setBackground(new java.awt.Color(255, 255, 255));
        btEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/EnviarMensaje.png"))); // NOI18N
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 416, 48, 35));

        btFacturar.setBackground(new java.awt.Color(255, 255, 255));
        btFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/1445655204_bill.png"))); // NOI18N
        btFacturar.setText("Facturar");
        getContentPane().add(btFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 10, 150, -1));

        txtMensaje.setText("Mensaje");
        txtMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajeActionPerformed(evt);
            }
        });
        getContentPane().add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 416, 211, 35));

        Chat_Servidor.setEditable(false);
        Chat_Servidor.setColumns(20);
        Chat_Servidor.setRows(5);
        jScrollPane1.setViewportView(Chat_Servidor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 505, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/portada8.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 460));

        MenuBarPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        MenuBarPrincipal.setBorder(new javax.swing.border.MatteBorder(null));
        MenuBarPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        menuMantenimientos.setForeground(new java.awt.Color(255, 255, 255));
        menuMantenimientos.setText("Mantenimientos");

        menuManteCliente.setBackground(new java.awt.Color(255, 255, 255));
        menuManteCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/user.png"))); // NOI18N
        menuManteCliente.setText("Cliente");
        menuManteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManteClienteActionPerformed(evt);
            }
        });
        menuMantenimientos.add(menuManteCliente);

        menuManteArticulo.setBackground(new java.awt.Color(255, 255, 255));
        menuManteArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/ManteArticulo.png"))); // NOI18N
        menuManteArticulo.setText("Articulo");
        menuManteArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManteArticuloActionPerformed(evt);
            }
        });
        menuMantenimientos.add(menuManteArticulo);

        menuManteProveedor.setBackground(new java.awt.Color(255, 255, 255));
        menuManteProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/call-center-icon.png"))); // NOI18N
        menuManteProveedor.setText("Proveedor");
        menuManteProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManteProveedorActionPerformed(evt);
            }
        });
        menuMantenimientos.add(menuManteProveedor);

        menuManteArtProv.setBackground(new java.awt.Color(255, 255, 255));
        menuManteArtProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/providers.png"))); // NOI18N
        menuManteArtProv.setText("Articulo por Proveedor");
        menuManteArtProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManteArtProvActionPerformed(evt);
            }
        });
        menuMantenimientos.add(menuManteArtProv);

        MenuBarPrincipal.add(menuMantenimientos);

        MenuReportes.setForeground(new java.awt.Color(255, 255, 255));
        MenuReportes.setText("Reportes");

        mReporteClientes.setBackground(new java.awt.Color(255, 255, 255));
        mReporteClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/Reports.png"))); // NOI18N
        mReporteClientes.setText("Clientes");
        mReporteClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReporteClientesActionPerformed(evt);
            }
        });
        MenuReportes.add(mReporteClientes);

        mReporteArticulos.setBackground(new java.awt.Color(255, 255, 255));
        mReporteArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/Reports.png"))); // NOI18N
        mReporteArticulos.setText("Articulos");
        mReporteArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReporteArticulosActionPerformed(evt);
            }
        });
        MenuReportes.add(mReporteArticulos);

        mReporteFacturas.setBackground(new java.awt.Color(255, 255, 255));
        mReporteFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/Reports.png"))); // NOI18N
        mReporteFacturas.setText("Facturas");
        mReporteFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReporteFacturasActionPerformed(evt);
            }
        });
        MenuReportes.add(mReporteFacturas);

        mReporteProveedores.setBackground(new java.awt.Color(255, 255, 255));
        mReporteProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/una/prograIII/appProyecto/vista/imagenes/Reports.png"))); // NOI18N
        mReporteProveedores.setText("Proveedores");
        mReporteProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReporteProveedoresActionPerformed(evt);
            }
        });
        MenuReportes.add(mReporteProveedores);

        MenuBarPrincipal.add(MenuReportes);

        setJMenuBar(MenuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuManteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManteClienteActionPerformed
    
    }//GEN-LAST:event_menuManteClienteActionPerformed

    private void menuManteArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManteArticuloActionPerformed
        
    }//GEN-LAST:event_menuManteArticuloActionPerformed

    private void menuManteProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManteProveedorActionPerformed
        
    }//GEN-LAST:event_menuManteProveedorActionPerformed

    private void menuManteArtProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManteArtProvActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_menuManteArtProvActionPerformed

    private void btLimpiarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarPantallaActionPerformed

    }//GEN-LAST:event_btLimpiarPantallaActionPerformed

    private void btDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesbloquearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDesbloquearActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEnviarActionPerformed

    private void txtMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensajeActionPerformed

    private void mReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReporteClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mReporteClientesActionPerformed

    private void mReporteArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReporteArticulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mReporteArticulosActionPerformed

    private void mReporteFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReporteFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mReporteFacturasActionPerformed

    private void mReporteProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReporteProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mReporteProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaPrincipal p = new PantallaPrincipal();
                p.setVisible(true);
                p.setResizable(false);
                          
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Chat_Servidor;
    private javax.swing.JMenuBar MenuBarPrincipal;
    public javax.swing.JMenu MenuReportes;
    public javax.swing.JButton btBloquear;
    public javax.swing.JButton btDesbloquear;
    public javax.swing.JButton btDetenerServidor;
    public javax.swing.JButton btEnviar;
    public javax.swing.JButton btFacturar;
    public javax.swing.JButton btIniciarServidor;
    public javax.swing.JButton btLimpiarPantalla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTPC;
    public javax.swing.JMenuItem mReporteArticulos;
    public javax.swing.JMenuItem mReporteClientes;
    public javax.swing.JMenuItem mReporteFacturas;
    public javax.swing.JMenuItem mReporteProveedores;
    public javax.swing.JMenuItem menuManteArtProv;
    public javax.swing.JMenuItem menuManteArticulo;
    public javax.swing.JMenuItem menuManteCliente;
    public javax.swing.JMenuItem menuManteProveedor;
    public javax.swing.JMenu menuMantenimientos;
    public javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables

    
}
