/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.una.prograIII.appProyecto.vista;
import cr.ac.una.prograIII.appProyecto.bl.ArtProvBL;
import cr.ac.una.prograIII.appProyecto.bl.ClienteBL;
import cr.ac.una.prograIII.appProyecto.controlador.ArtProvControlador;
import cr.ac.una.prograIII.appProyecto.controlador.ClienteControlador;
import cr.ac.una.prograIII.appProyecto.vista.ManteArtProv;
import cr.ac.una.prograIII.appProyecto.vista.PantallaPrincipal;
import cr.ac.una.prograIII.appProyecto.vista1.ManteCliente;
import cr.ac.una.prograIII.appProyecto.bl.ArtProvBL;
import cr.ac.una.prograIII.appProyecto.bl.ArticuloBL;
import cr.ac.una.prograIII.appProyecto.bl.ClienteBL;
import cr.ac.una.prograIII.appProyecto.bl.ProveedorBL;
import cr.ac.una.prograIII.appProyecto.controlador.ArtProvControlador;
import cr.ac.una.prograIII.appProyecto.controlador.ArticuloControlador;
import cr.ac.una.prograIII.appProyecto.controlador.ClienteControlador;
import cr.ac.una.prograIII.appProyecto.controlador.PcControlador;
import cr.ac.una.prograIII.appProyecto.controlador.ProveedorControlador;
import cr.ac.una.prograIII.appProyecto.domain.Pc;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class PantallaPrincipal extends javax.swing.JFrame implements ActionListener {
    ArrayList<Pc> lista= new ArrayList();
    int c=0;
    boolean primeravez=true;
    int agregados=0;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLayout(null);
        this.cargaPc.addActionListener(this);
        
        
        /*JButton bt=new JButton();
        bt.setText("hola");
        bt.setVisible(true);
        bt.setBounds(30,25,100,30);
        
        add(bt);*/
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jMenuItem3 = new javax.swing.JMenuItem();
        cargaPc = new javax.swing.JButton();
        MenuBarPrincipal = new javax.swing.JMenuBar();
        MenuMatenimiento = new javax.swing.JMenu();
        MnuItemCliente = new javax.swing.JMenuItem();
        MnuItemArticulo = new javax.swing.JMenuItem();
        MnuItemProveedor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnuItemPc = new javax.swing.JMenuItem();
        MenuFacturacion = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        MenuBuscar = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jButton1.setText("jButton1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cargaPc.setText("Cargar Pc");
        cargaPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaPcActionPerformed(evt);
            }
        });

        MenuBarPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        MenuMatenimiento.setText("Mantenimientos");

        MnuItemCliente.setBackground(new java.awt.Color(255, 255, 255));
        MnuItemCliente.setText("Cliente");
        MnuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuItemClienteActionPerformed(evt);
            }
        });
        MenuMatenimiento.add(MnuItemCliente);

        MnuItemArticulo.setBackground(new java.awt.Color(255, 255, 255));
        MnuItemArticulo.setText("Articulo");
        MnuItemArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuItemArticuloActionPerformed(evt);
            }
        });
        MenuMatenimiento.add(MnuItemArticulo);

        MnuItemProveedor.setBackground(new java.awt.Color(255, 255, 255));
        MnuItemProveedor.setText("Proveedor");
        MnuItemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuItemProveedorActionPerformed(evt);
            }
        });
        MenuMatenimiento.add(MnuItemProveedor);

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Articulo por Proveedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuMatenimiento.add(jMenuItem1);

        MnuItemPc.setText("PC");
        MnuItemPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuItemPcActionPerformed(evt);
            }
        });
        MenuMatenimiento.add(MnuItemPc);

        MenuBarPrincipal.add(MenuMatenimiento);

        MenuFacturacion.setText("Facturacion");

        jMenuItem23.setText("Facturar");
        MenuFacturacion.add(jMenuItem23);

        MenuBarPrincipal.add(MenuFacturacion);

        MenuBuscar.setText("Buscar");

        jMenuItem10.setText("Usuario");
        MenuBuscar.add(jMenuItem10);

        jMenuItem11.setText("Cliente");
        MenuBuscar.add(jMenuItem11);

        jMenuItem12.setText("Proveedor");
        MenuBuscar.add(jMenuItem12);

        MenuBarPrincipal.add(MenuBuscar);

        MenuReportes.setText("Reportes");

        jMenu13.setText("Facturas");
        MenuReportes.add(jMenu13);

        jMenu14.setText("Clientes");
        MenuReportes.add(jMenu14);

        jMenu16.setText("Articulos");
        MenuReportes.add(jMenu16);

        MenuBarPrincipal.add(MenuReportes);

        setJMenuBar(MenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cargaPc)
                .addGap(0, 326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cargaPc)
                .addGap(0, 244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuItemClienteActionPerformed
        ManteCliente manteClienteView = new ManteCliente();
        ClienteBL clienteBLModelo = new ClienteBL();
        ClienteControlador cC = new ClienteControlador(manteClienteView, clienteBLModelo);
        cC.getMantClienteView().setVisible(true);
    }//GEN-LAST:event_MnuItemClienteActionPerformed

    private void MnuItemArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuItemArticuloActionPerformed
        ManteArticulo mateArticuloview = new ManteArticulo();
        ArticuloBL articuloBlModelo = new ArticuloBL();
        ArticuloControlador articuloc = new ArticuloControlador(mateArticuloview, articuloBlModelo);
        articuloc.getMantArticuloView().setVisible(true);
    }//GEN-LAST:event_MnuItemArticuloActionPerformed

    private void MnuItemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuItemProveedorActionPerformed
        ManteProveedor manteProveedorView = new ManteProveedor();
        ProveedorBL proveedorBlModelo = new ProveedorBL();
        ProveedorControlador provControlador = new ProveedorControlador(manteProveedorView, proveedorBlModelo);
        provControlador.getMantProveedorView().setVisible(true);
    }//GEN-LAST:event_MnuItemProveedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ManteArtProv manteAp = new ManteArtProv();
        ArtProvBL apBL = new ArtProvBL();
        ArtProvControlador apc = new ArtProvControlador(manteAp, apBL);
        apc.getManteArtProvView().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MnuItemPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuItemPcActionPerformed
        MantePc mantPc=new MantePc();
        c=lista.size();
        PcControlador pcControl= new PcControlador(mantPc, lista, c,this);
        pcControl.getMantPc().setVisible(true);
        
    }//GEN-LAST:event_MnuItemPcActionPerformed

    private void cargaPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaPcActionPerformed
        
    }//GEN-LAST:event_cargaPcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaPrincipal p = new PantallaPrincipal();
                p.setVisible(true);
                p.setResizable(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBarPrincipal;
    private javax.swing.JMenu MenuBuscar;
    private javax.swing.JMenu MenuFacturacion;
    private javax.swing.JMenu MenuMatenimiento;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenuItem MnuItemArticulo;
    private javax.swing.JMenuItem MnuItemCliente;
    private javax.swing.JMenuItem MnuItemPc;
    private javax.swing.JMenuItem MnuItemProveedor;
    public javax.swing.JButton cargaPc;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==cargaPc){
            int ejex=50;
            int ejey=40;
            int inix=0;
            int iniy=0;
            if(primeravez){
        for(int x=0;x<lista.size();x++){
            lista.get(x).addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    Pc actual= (Pc) e.getSource();
                    JOptionPane.showMessageDialog(rootPane, "Click");
                }
            });
            lista.get(x).setVisible(true);
            lista.get(x).setBounds(inix+ejex,iniy+ejey,100,30);
            inix+=ejex;
            iniy+=ejey;
            
            this.add(lista.get(x));
            JOptionPane.showMessageDialog(rootPane, "Lo hizo");
            agregados++;
            primeravez=false;
        }   
        }else{
                for(int x=lista.size()-agregados;x<lista.size();x++){
            lista.get(x).addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    Pc actual= (Pc) e.getSource();
                    JOptionPane.showMessageDialog(rootPane, "Click");
                }
            });
            lista.get(x).setVisible(true);
            lista.get(x).setBounds(inix+ejex,iniy+ejey,50,50);
            inix+=ejex;
            iniy+=ejey;
            
            this.add(lista.get(x));
            JOptionPane.showMessageDialog(rootPane, "Lo hizo");
            agregados++;
        }   
            
                
            }
        }
        
    }
}
